apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexus
resources:
  - namespace.yaml
  - nexus-pv.yaml
  - nexus-deployment.yaml
  - nexus-service.yaml
  - nexus-ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: nexus
