apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  type: ClusterIP
  ports:
  - name: nexus-web
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: docker-registry
    port: 8082
    targetPort: 8082
    protocol: TCP
  - name: npm-registry
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: nexus
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-nodeport
  namespace: nexus
  labels:
    app: nexus
spec:
  type: NodePort
  ports:
  - name: nexus-web
    port: 8081
    targetPort: 8081
    nodePort: 30081
  - name: docker-registry
    port: 8082
    targetPort: 8082
    nodePort: 30082
  - name: npm-registry
    port: 8083
    targetPort: 8083
    nodePort: 30083
  selector:
    app: nexus
