apiVersion: v1
kind: Namespace
metadata:
  name: vllm
  labels:
    app.kubernetes.io/part-of: vllm
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
