apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: vllm
  labels:
    app: vllm
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: vllm
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-nodeport
  namespace: vllm
  labels:
    app: vllm
    app.kubernetes.io/part-of: vllm
spec:
  type: NodePort
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30800
      protocol: TCP
