apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm
labels:
  - pairs:
      app.kubernetes.io/part-of: vllm
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/cluster: kind
    includeSelectors: false
    includeTemplates: false
resources:
  - ../../../components/distill
  - ../../../components/distill-export
  - ../finetune-pvc
patches:
  - path: collector-patch.yaml
  - path: export-patch.yaml

images:
  - name: distill-collector
    newName: distill-collector
    newTag: 3.11-aiohttp
