apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: nginx
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: false
