apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 10.0.0.0/8
    - 192.168.0.0/16
    - 172.16.0.0/12
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080
      targetPort: 80 ##nginx-deployment.yamlのcontainerPortと同値
