apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elk-stack
resources:
  - namespace.yaml
  - elasticsearch-configmap.yaml
  - elasticsearch-deployment.yaml
  - elasticsearch-index-template.yaml
  - elasticsearch-pv.yaml
  - elasticsearch-service.yaml
  - kibana-configmap.yaml
  - kibana-dashboard-config.yaml
  - kibana-deployment.yaml
  - kibana-service.yaml
  - kibana-ingress.yaml
  - logstash-configmap.yaml
  - logstash-deployment.yaml
  - logstash-service.yaml
  - log-generator-cronjob.yaml
  - winlogbeat-config.yaml
commonLabels:
  app.kubernetes.io/part-of: elk-stack
